# Generated by Django 5.2.4 on 2025-07-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0002_remove_customuser_is_profesor_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionrecord',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
